added example flow document
ace-ecosystem/ace2-core pull request #2
Opened 2020-12-30 01:37 UTC by krayzpipes

Example flow documentation

2020-12-30 02:13 UTC, unixfreak0037 requested changes
A couple of suggestions here.

- Take VT and File Hash analysis out of the example to make the example more simple.
- Word Document should have a dependency on File Type (looking for the type of the file before deciding to analyze it as a word document.)

2020-12-30 03:13 UTC, krayzpipes commented
> A couple of suggestions here.
> 
> * Take VT and File Hash analysis out of the example to make the example more simple.
> * Word Document should have a dependency on File Type (looking for the type of the file before deciding to analyze it as a word document.)

@unixfreak0037  - I was thinking the observable type `file:word_doc` would show that there was a file type dependency. I am assuming based on your feedback that you have some other way you want to represent that in the article?  If so, is there another analysis/observable metadata value that should be set to show that dependency?

2020-12-30 14:01 UTC, unixfreak0037 commented
> > A couple of suggestions here.
> > 
> > * Take VT and File Hash analysis out of the example to make the example more simple.
> > * Word Document should have a dependency on File Type (looking for the type of the file before deciding to analyze it as a word document.)
> 
> @unixfreak0037 - I was thinking the observable type `file:word_doc` would show that there was a file type dependency. I am assuming based on your feedback that you have some other way you want to represent that in the article? If so, is there another analysis/observable metadata value that should be set to show that dependency?

Yeah that would be in the registration of the module [here](https://github.com/ace-ecosystem/ace2-core/blob/main/ace/data_model.py#L33) I just pushed [another change](https://github.com/ace-ecosystem/ace2-core/pull/2/commits/5fa65c3ff3abc15f473623d473bd79235822e28a), does that look good?

2021-01-02 19:55 UTC, unixfreak0037 approved these changes

2021-01-02 19:55 UTC, merged